### ISSUE TITLE
BUG (Med Priority): Leftmost Column Recognition

### ISSUE THREAD

**Issue by Zwky26** [OHDSI/Perseus#1]
SQL Functions fail to recognize the leftmost column of a table

![image](https://user-images.githubusercontent.com/59004211/182199693-2b00e05f-7a04-4ded-ae1e-252b8254db7a.png)

Renaming "primary_code" to "p_code" does not resolve issue. Swapping the position of the two columns in the csv reveals that it is not recognizing the leftmost column name
![image](https://user-images.githubusercontent.com/59004211/182199833-5b1f92aa-1f3e-412e-b8eb-8b9ef2381f4b.png)

Error occurs for tables, seemingly regardless of how many total columns there are (1-20 columns) BUT this issue does not occur for user-created Views.

**Comment by bradanton** [comment]
@Zwky26 Could you please share csv file?

**Comment by Zwky26** [comment]
Here is a generic csv that I used. I have experimented with different column names, number of columns, and number of rows- the error seems to persist with any csv I try

[test2.csv](https://github.com/OHDSI/Perseus/files/9251877/test2.csv)

**Comment by bradanton** [comment]
Hi @Zwky26,

Looks like it is encoding issue, file has UTF8 with BOM that's why it has U+FEFF BYTE ORDER MARK at the start of a text stream.

I will add fix, before that you can use UTF8 without BOM or visual type of SQL function. 

![image](https://user-images.githubusercontent.com/13117785/182817030-76f48be6-5609-4775-96f6-40cf3ebde9af.png)

**Comment by bradanton** [comment]
@Zwky26 FIXED

**Comment by ssamus** [comment]
@Zwky26  item was done. please check it out

**Comment by Zwky26** [comment]
Tested and approved
